urls = [
    'https://github.com/kev-m/pyCoilGen',
    'https://github.com/imr-framework/virtual-scanner',
    'https://github.com/umbertozanovello/CoSimPy',
    'https://github.com/vespa-mrs/vespa',
    'https://github.com/brain-link/scanhub',
    'https://github.com/Slicer/Slicer',
    'https://github.com/eptlib/eptlib',
    'https://github.com/SyneRBI/SIRF?tab=readme-ov-file',
    'https://github.com/shakes76/sHDR',
    'https://github.com/gadgetron/gadgetron',
    'https://github.com/mrfil/PowerGrid',
    'https://github.com/pnlbwh/ukftractography',
    'https://github.com/SCAN-NRAD/DL-DiReCT',
    'https://github.com/dafne-imaging/dafne',
    'https://github.com/UKRIN-MAPS/ukat',
    'https://github.com/imr-framework/pypulseq',
    'https://github.com/spinalcordtoolbox/spinalcordtoolbox',
    'https://github.com/mmromero/dwybss',
    'https://github.com/freesurfer/freesurfer',
    'https://github.com/SimpleITK/SimpleITK',
    'https://github.com/ismrmrd/ismrmrd',
    'https://github.com/mrphys/tensorflow-mri',
    'https://github.com/spinicist/QUIT',
    'https://github.com/michaelberks/madym_python',
    'https://github.com/JuliaHealth/KomaMRI.jl',
    'https://github.com/mloecher/gropt',
    'https://github.com/kerkelae/disimpy',
    'https://github.com/fsantini/MyoQMRI',
    'https://github.com/JakobAsslaender/MRIgeneralizedBloch.jl',
    'https://github.com/jondeuce/DECAES.jl',
    'https://github.com/MagneticResonanceImaging/MRIReco.jl',
    'https://github.com/ccipd/MRQy',
    'https://github.com/samuelstjean/nlsam',
    'https://github.com/mrirecon/bart',
    'https://github.com/MRtrix3/mrtrix3',
    'https://github.com/nipreps/smriprep',
    'https://github.com/facebookresearch/fastMRI',
    'https://github.com/saitta-s/flow4D',
    'https://github.com/daviddmc/NeSVoR',
    'https://github.com/allard-shi/affirm',
    'https://github.com/gift-surg/NiftyMIC',
    'https://github.com/SVRTK/SVRTK',
    'https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit',
    'https://github.com/daviddmc/fetal-IQA',
    'https://github.com/korbinian90/MriResearchTools.jl',
    'https://github.com/JuliaNeuroscience/NIfTI.jl',
    'https://github.com/davidssmith/DCEMRI.jl',
    'https://github.com/ai-med/quickNAT_pytorch',
    'https://github.com/poldracklab/pydeface',
    'https://github.com/danishm/mritopng',
    'https://github.com/cMadan/openMorph',
    'https://github.com/PennLINC/qsiprep',
    'https://github.com/miykael/gif_your_nifti',
    'https://github.com/cwatson/brainGraph',
    'https://github.com/NKI-AI/direct',
    'https://github.com/neuroneural/brainchop',
    'https://github.com/nipreps/mriqc',
    'https://github.com/BBillot/SynthSeg',
    'https://github.com/jcreinhold/intensity-normalization',
    'https://github.com/epam/mriviewer',
    'https://github.com/Project-MONAI/MONAI',
    'https://github.com/MIC-DKFZ/medicaldetectiontoolkit',
    'https://github.com/fepegar/torchio',
    'https://github.com/deepmedic/deepmedic',
    'https://github.com/perone/medicaltorch?tab=readme-ov-file',
    'https://github.com/black0017/MedicalZooPytorch',
    'https://github.com/nipy/nipype',
    'https://github.com/nipy/nibabel',
    'https://github.com/nipy/nipy',
    'https://github.com/nipy/nitime',
    'https://github.com/kdesimone/popeye',
    'https://github.com/nilearn/nilearn',
    'https://github.com/PyMVPA/PyMVPA',
    'https://github.com/MIC-DKFZ/TractSeg',
    'https://github.com/aramis-lab/clinicadl',
    'https://github.com/neuronflow/BraTS-Toolkit',
    'https://github.com/Open-Minds-Lab/mrQA',
    'https://github.com/GSTT-CSC/hazen',
    'https://github.com/EGates1/MRDQED',
    'https://github.com/felixhorger/MRISafety.jl',
    'https://github.com/nipreps/niworkflows'
]
